import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: "#f8f9fa",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    backgroundColor: "#ffffff",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginLeft: 16,
    flex: 1,
  },
  rightHeaderPlaceholder: {
    width: 40,
  },
  masonryListContainer: {
    paddingHorizontal: 6,
    paddingTop: 10,
  },
  gridItemContainer: {
    flex: 1,
    margin: 6,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    maxWidth: "48%",
    shadowRadius: 2,
    elevation: 2,
    overflow: "hidden",
  },
  gridItemImage: {
    width: "100%",
    height: 150,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  gridItemDetails: {
    padding: 10,
  },
  gridItemTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 3,
  },
  gridItemPrice: {
    fontSize: 13,
    color: "#28a745",
    fontWeight: "600",
    marginBottom: 3,
  },
  gridItemCreators: {
    fontSize: 12,
    color: "#6c757d",
    marginBottom: 5,
  },
  gridItemIssue: {
    fontSize: 12,
    color: "#555",
    marginTop: 2,
  },
  reservationInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  reservationQuantity: {
    fontSize: 12,
    color: "#333",
  },
  reservationStatus: {
    fontSize: 12,
    color: "#1A237E",
    fontWeight: "500",
  },
  availabilityContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  availableText: {
    fontSize: 12,
    color: "#28a745",
    fontWeight: "500",
    marginBottom: 5,
  },
  unavailableText: {
    fontSize: 12,
    color: "#dc3545",
    fontWeight: "500",
  },
  addToCartButton: {
    backgroundColor: "#1A237E",
    padding: 8,
    borderRadius: 4,
    alignItems: "center",
    marginTop: 4,
  },
  addToCartDisabled: {
    backgroundColor: "#ccc",
    padding: 8,
    borderRadius: 4,
    alignItems: "center",
    marginTop: 4,
  },
  addToCartText: {
    color: "white",
    fontSize: 12,
    fontWeight: "500",
  },
  messageText: {
    fontSize: 16,
    color: "#555",
    textAlign: "center",
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: "#dc3545",
    marginTop: 8,
    textAlign: "center",
  },
  placeholderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
  },
  placeholderImage: {
    width: 120,
    height: 120,
    marginBottom: 18,
    opacity: 0.2,
  },
});
